Scrum 15/update user
sunggyu-organization/companity pull request #3
Opened 2024-06-05 01:54 UTC by ohj4312

### 닉네임 수정
- PATCH /users/:id
- request param : userId
- BODY : 
```
{
    nickName : nickName
}
```

2024-06-11 01:54 UTC, nsnnsn12 requested changes

2024-06-11 01:54 UTC, nsnnsn12 commented on src/main/java/com/codecrafters/companity/adapter/user/UserController.java
> +    @PatchMapping("/{userId}/nick-name")
업데이트할 때 주로 put이 아닌 patch를 사용한 이유가 궁금

2024-06-11 01:54 UTC, nsnnsn12 commented on src/main/java/com/codecrafters/companity/application/in/usecase/UserUseCase.java
> +    public User signUp(UserCreateRequest request);
controller와 usecase dto를 분리 여부 결정 필요

2024-06-11 01:54 UTC, nsnnsn12 commented on src/test/java/com/codecrafters/companity/application/service/user/UserServiceTest.java
> +        Assertions.assertAll(() -> {
테스트를 위한 라이브러리 통일 필요

2024-06-13 08:15 UTC, ohj4312 commented on src/main/java/com/codecrafters/companity/adapter/user/UserController.java
> +    @PatchMapping("/{userId}/nick-name")
요구 사항이 user 를 수정하는 것이 아닌 닉네임 변경이기 때문입니다

2024-06-13 08:16 UTC, ohj4312 commented on src/main/java/com/codecrafters/companity/application/in/usecase/UserUseCase.java
> +    public User signUp(UserCreateRequest request);
오버 엔지니어링이지만, 학습의 필요성으로 구분 짓는다는 것에 동의

2024-06-13 08:34 UTC, ohj4312 commented on src/test/java/com/codecrafters/companity/application/service/user/UserServiceTest.java
> +        Assertions.assertAll(() -> {
조합하여 사용하는 방향으로 Assertions 문법은 AssertJ 로 변경하는 게 좋겠군요. 👍 
- Assertions.assertAll 문법은 AssertJ 의 SoftAssertions / assertAll() 대체 가능

2024-06-20 02:15 UTC, nsnnsn12 approved these changes

2024-06-26 01:14 UTC, merged